/* Generated By:JavaCC: Do not edit this line. JsonTreeConstants.java Version 5.0 */
package json;

public interface JsonTreeConstants
{
  public int JJTSTART_EXP = 0;
  public int JJTVOID = 1;
  public int JJTNODES = 2;
  public int JJTLINKS = 3;
  public int JJTNODE = 4;
  public int JJTLINK = 5;
  public int JJTLETTER = 6;
  public int JJTINT = 7;
  public int JJTSYNTATICERROR = 8;


  public String[] jjtNodeName = {
    "Start_Exp",
    "void",
    "nodes",
    "links",
    "node",
    "link",
    "Letter",
    "Int",
    "SyntaticError",
  };
}
/* JavaCC - OriginalChecksum=0656dd849cf519cc5205cf7255ba3f8c (do not edit this line) */
