/* Generated By:JavaCC: Do not edit this line. JsonTreeConstants.java Version 5.0 */
package json;

public interface JsonTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPRESSION1 = 1;
  public int JJTEXPRESSION2 = 2;
  public int JJTEXPRESSION3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Expression1",
    "Expression2",
    "Expression3",
  };
}
/* JavaCC - OriginalChecksum=ce94549adb32907c97753b6f5f4538ed (do not edit this line) */
