/* Generated By:JJTree&JavaCC: Do not edit this line. JsonConstants.java */
package json;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JsonConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NODES = 5;
  /** RegularExpression Id. */
  int LINKS = 6;
  /** RegularExpression Id. */
  int NAME = 7;
  /** RegularExpression Id. */
  int GROUP = 8;
  /** RegularExpression Id. */
  int SOURCE = 9;
  /** RegularExpression Id. */
  int TARGET = 10;
  /** RegularExpression Id. */
  int VALUE = 11;
  /** RegularExpression Id. */
  int QUOTE = 12;
  /** RegularExpression Id. */
  int SHAPE = 13;
  /** RegularExpression Id. */
  int STYLE = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int LETTER = 16;
  /** RegularExpression Id. */
  int OBRACKET = 17;
  /** RegularExpression Id. */
  int CBRACKET = 18;
  /** RegularExpression Id. */
  int OBRA = 19;
  /** RegularExpression Id. */
  int CBRA = 20;
  /** RegularExpression Id. */
  int TD = 21;
  /** RegularExpression Id. */
  int COMMA = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\\"nodes\\\"\"",
    "\"\\\"links\\\"\"",
    "\"\\\"name\\\"\"",
    "\"\\\"group\\\"\"",
    "\"\\\"source\\\"\"",
    "\"\\\"target\\\"\"",
    "\"\\\"value\\\"\"",
    "\"\\\"\"",
    "\"\\\"shape\\\"\"",
    "\"\\\"style\\\"\"",
    "<INTEGER>",
    "<LETTER>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
  };

}
